project:
  type: website
  
website:
  title: "openwashdata"
  site-url: https://openwashdata.org/
  description: "Website of the openwashdata community"
  page-navigation: true
  search: false
  page-footer: 
    left: | 
        This project was supported by the 
        [Open Research Data Program of the ETH Board](https://ethrat.ch/en/eth-domain/open-research-data/)
    right:
      - text: About
        href: about.qmd
      - icon: "envelope-at"
        href: "mailto:ghe@mavt.ethz.ch?subject=openwashdata support"
        aria-label: Email
      - icon: github
        href: https://github.com/openwashdata
        aria-label: GitHub
      - icon: chat-left-dots
        href: https://matrix.to/#/#openwashdata-lobby:staffchat.ethz.ch
        aria-label: Matrix

  announcement: 
    icon: info-circle
    dismissable: true
    content: "[**Re-advertised open position:**](https://openwashdata.org/pages/blog/posts/2024-09-16-ukzn-data-steward) - come work with us on data stewardship at [UKZN WASH R&D Centre, South Africa](https://openwashdata.org/pages/blog/posts/2024-09-16-ukzn-data-steward)."
    type: info
    position: below-navbar

  navbar:
    background: "#5b195b"
    title: false
    logo: "images/OWD-logo-04.png"
    logo-alt: "openwashdata logo."
    favicon: "images/OWD-logo-18.png"
    collapse-below: lg
    left:
      - text: " "
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Get Started"
        href: pages/get-started/index.qmd
      - text: "Data"
        href: pages/gallery/data/index.qmd
      - text: "Academy"
        menu: 
          - text: "Courses"
            href: pages/academy/index.qmd
          - text: "Graduates 2024"
            href: pages/academy/graduates/index.qmd
      - text: "Gallery"
        href: pages/gallery/
      - text: "Events"
        href: pages/events/index.qmd
      - text: "Blog"
        href: pages/blog/index.qmd
      - text: "Partners"
        href: pages/partners/index.qmd
      - text: "Support"
        menu:
          - text: "Email us"
            icon: "envelope-at"
            href: "mailto:ghe@mavt.ethz.ch?subject=openwashdata support"
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/openwashdata/book/issues"
          - text: "Donate data"
            icon: "clipboard-data"
            href: "https://github.com/openwashdata/data/issues"

    right:
      - text: Code of Conduct
        href: code_of_conduct.qmd
      - icon: envelope-at-fill
        href: "mailto:ghe@mavt.ethz.ch?subject=openwashdata support"
        aria-label: Email
      - icon: github
        href: https://github.com/openwashdata
        aria-label: GitHub

  sidebar:
    - id: get-started
      title: "Get Started"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - pages/get-started/index.qmd
        - text: "Chat"
          href: pages/get-started/chat/index.qmd
          
    - id: gallery
      title: "Gallery"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - text: "Data"
          href: pages/gallery/data/index.qmd
        - text: "VMOST"
          href: pages/gallery/vmost/index.qmd
        - text: "Stats"
          href: pages/gallery/stats/index.qmd
        - text: "Slides"
          href: pages/gallery/slides/
        - text: "Phase 1 Proposal"
          href: pages/gallery/proposal/index.qmd
        - text: "Phase 2 Proposal"
          href: pages/gallery/proposal-02/index.qmd
        
format:
  html:
    theme:
      light: [litera, style/theme.scss]
    highlight-style: a11y-dark
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    mainfont: "Atkinson Hyperlegible"
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    include-in-header: 
        - text: |
            <script defer data-domain="openwashdata.org" src="https://plausible.io/js/script.js"></script>

execute: 
  freeze: auto
