project:
  type: website

website:
  title: "openwashdata"
  page-navigation: true
  search: false
  page-footer: 
    left: | 
        This project was supported by the 
        [Open Research Data Program of the ETH Board](https://ethrat.ch/en/eth-domain/open-research-data/)
  navbar:
    background: "#5b195b"
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Events"
        href: pages/events/index.qmd
      - text: "Gallery"
        href: pages/gallery/index.qmd
      - text: "Proposal"
        href: pages/proposal/index.qmd
      - text: "Help"
        menu:
          - text: "Donate data"
            icon: "clipboard-data"
            href: "https://github.com/openwashdata/data/issues"
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/openwashdata/book/issues"

    right:
      - icon: twitter
        href: https://twitter.com/openwashdata
        aria-label: Twitter
      - icon: github
        href: https://github.com/openwashdata
        aria-label: GitHub
        
format:
  html:
    theme: [cosmo, theme.scss]
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
    include-in-header: 
        - text: |
            <script defer data-domain="openwashdata.org" src="https://plausible.io/js/script.js"></script>

execute: 
  freeze: auto
