project:
  type: website

website:
  title: "openwashdata"
  page-navigation: true
  search: false
  page-footer: 
    left: | 
        This project was supported by the 
        [Open Research Data Program of the ETH Board](https://ethrat.ch/en/eth-domain/open-research-data/)
  navbar:
    background: primary
    title: false
    collapse-below: lg
    left: 
      - text: "Overview"
        href: index.qmd
        
format:
  html:
    theme: [cosmo, theme.scss]
    css: styles.css
    toc: true



