---
title: Internship - Data Science with openwashdata - 80% or more
subtitle: A unique opportunity to apply your data science skills to real-world problems in the WASH sector.
description: |
  Join our team for 6 months and support us in building the openwashdata community while learning about
  open science, open research data, reproducibility, SDG6, and WASH.
categories:
  - internship
  - data science
  - R
author: Lars Schöbitz
date: today
draft: false
image: "OWD-logo-12.svg"
image-alt: "openwashdata logo in orange"
format:
  html: 
    toc-location: right
  typst: 
    mainfont: "Arial"
---

## Background

As part of our Open Science team you will support us in developing efficient data cleaning processes, comprehensible visualizations, and teaching events that provide an inclusive and safe learning environment. Your efforts will primarily focus on projects related to our openwashdata community, funded by the [Open Research Data Program of the ETH Board](https://open-research-data-portal.ch/). Details can be found at <https://openwashdata.org>.

## Profile

This job is for you if:

- [you are enrolled in an MSc programme at ETH Zurich and are planning to take a holiday term or have already completed your degree work]{.highlight-yellow}
- you care about data and code being reusable
- you have been taught standard data science tools (e.g., Git, GitHub, R, Python, RStudio IDE, VS Code, etc.)
- you can clean, visualize, and communicate data using R, and ideally, the collection of R tidyverse packages
- you are looking for some hands-on data science experience

## What's in it for you

Everyone is welcome here, just as they are. Our collegial and respectful interaction creates a pleasant working atmosphere and room for new ideas. In addition to a central work location in Zurich with plenty of room and sun in your office, you can work occasionally from home. The employment conditions follow the university guidelines. They include, for example, five weeks of vacation per year and a salary of 3,000 CHF per month at 100%. Read an experience report of a completed internship:

- <https://openwashdata.org/pages/blog/posts/2024-06-20-internship-report-02/>.

## Dates

- 2025-07-11: due date for submission of application
- 2025-07-14: notification about passing first selection round (two selected candidates)
- 2025-07-21: a personal and a technical interview
- 2025-07-23: notification about selection
- 2025-09-01: ideal start date, but flexible

## Submission requirements

An email to <a href="mailto:lschoebitz@ethz.ch?subject=Internship - Data Science with openwashdata" target="_blank">lschoebitz@ethz.ch</a> with an updated CV and a link to an online portfolio of previous work that shows the programming code for a data analysis project. If no public portfolio exists, a script with programming code can be submitted with the application package.
