---
title: Openwashdata 101
categories:
author: 
  - name: "Mian Zhong"
    affiliation: Global Health Engineering, ETH Zurich
    affiliation_url: https://ghe.ethz.ch/
    orcid_id: 0009-0009-4546-7214
date: 2023-07-03

draft: true
---

Welcome! We are glad that you take this initiative to join the community of openwashdata! We hope this post not only helps you with a smooth start to collaborate with us on the openwashdata project, but also benefit you with long-term [open science practice](https://ethz.ch/en/research/open-science.html).

While our common goal is more accessible and shareable data in WASH community, we do have different backgrounds and skill-sets. So feel free to skip some parts that are familiar to you. On the other hand, if you find some terms confusing, like "R programming" or "Github", don't worry and [stay tuned with us](https://buttondown.email/openwashdata). We will provide more detailed posts about open data practice in the future!

# 1. Access and use openwashdata

You could directly involving with openwashdata project simply by using our data! 

-   If you are a researcher, you may analyze and cite our data in your scientific work.
-   If you are a lecturer, consider integrate our data into your training and course materials!
-   If you do business in WASH sector, you may refer to some of the updated data for your business cases.

The development team is constantly working on organizing, cleaning, and releasing [new datasets](https://openwashdata.org/pages/gallery/). <!-- TODO: link to the correct list of datasets--> The following sections introduce you two common ways to use openwashdata.

## Let's do R, why not 🥳

If you have worked with [R programming](https://www.r-project.org)[^1], we are actively developing new R data packages. You could access the data simply by installing the package in R and start from there. For example, 

[^1]: "A free software environment for statistical computing and graphics"

```{{r}}
# Install data package
install.packages()
# Import data package
library()

```

## Nah, just give me the files 😈

We are opinionated to discourage this direction because the analysis work with the data might be less reproducible. Nevertheless, for the moment, we still think it's good way to make data as accessible as possible.

For each published dataset, we offer the csv files (`.csv`) and the spreadsheets (.`xlsx`) and you can directly download from the associated website. For example, with ... dataset, you may find the files as shown in the following figure.

<!-- TODO: Insert an example figure here. -->

## Cite openwashdata
All datasets by default are released under CC-BY license. When using openwashdata, consider cite the data package to acknowledge data collectors and maintainers. Each dataset has its citation information on the documentation website. For example, you may find how to cite package ` ` here.


# 2. Share your data with openwashdata

You got some amazing data and love to share? Great! Become a contributor simply by getting started with some tools and submit your data with provided template!

## Get open science tools 

We all probably have some social media to share life updates. For an open science project, likewise, we need tools to help us share, track, and communicate progress. Hence, we have picked widely used tools as part of the starter-kit to build openwashdata project.

<!-- \\TODO: Connect the following dots  -->

-   ORCID: First, we would like to get an identifier
-   Github: digital headquarter\
-   MATRIX: like Slack or Messenger an instant message chatroom for openwashdata,

### ORCID

1.  [Register an ORCID](https://orcid.org/signin)

    a.  If your institute has an affiliation, you could choose "Access through your institution" to register and sign in.

    b.  Otherwise, you may opt in th "Google" or "Facebook" sign-in options.

    c.  If the above-mentioned options are not for you, click ["Register Now"](https://orcid.org/register) and follow the instructions.

2.  Save your ORCID number

### Github

1.  Go to [Sign up for Github](https://github.com/signup) and follow the instructions to get an account
2.  Open [openwashdata](https://github.com/openwashdata) github organization and click "Follow" on the upper right corner to connect with us on Github.



## Submit a data idea

Now you have a Github account

-    Log in Github, and go to our [data donation]()
-   
-   

## Collaborate with us

### MATRIX

1.  Join our chatroom [openwash-lobby](https://matrix.to/#/%23openwash-lobby:staffchat.ethz.ch)
2.  If you do not have an MATRIX account yet, follow [this instruction]() to set up!
3.  Say "hi" in openwash-lobby!
