---
title: "what's next?"
subtitle: "data stewardship for WASH Center"
author: 
  - name: "Lars Schöbitz"
    url: https://openwashdata.org/about/lars/
    affiliation: Global Health Engineering, ETH Zurich
    affiliation_url: https://ghe.ethz.ch/
date: 2025-02-06
date-format: long
format: 
  revealjs:
    logo: "../images/OWD-logo-20.png"
    theme: "../../../../style/slides.scss"
    transition: fade
    slide-number: true
    preview-links: auto
    footer: "[{{< fa link >}} openwashdata.org/pages/gallery/slides/](https://openwashdata.org/pages/gallery/slides/)"
editor: source
editor_options: 
  chunk_output_type: console
bibliography: ["../datasets.bib", "../cu-wash-symposium-2023-openwashdata/references.bib"]
---

```{r}

library(tidyverse)
library(ggthemes)
library(ggtext)
library(gt)

# set ggplot theme --------------------------------------------------------

ggplot2::theme_set(
    # Pick a starting theme
    ggplot2::theme_gray(base_size = 14) +
        # Add your favourite elements
        ggplot2::theme(
            axis.line = element_line(),
            panel.background = element_rect(fill = "white"),
            panel.grid.major = element_line("grey95", linewidth = 0.25),
            legend.key  = element_rect(fill = NA) 
        )
)

```

# WASH Center: Computational Competency {background-color="#5b195b"}

## Where do we stand?

- Computational competency is a key skill for solid research data management
- Survey: <https://forms.gle/XSyUJ5GrmzvXtTFN8>
- 24 responses

# FAIR data publishing workshop {background-color="#5b195b"}

## FAIR data publishing workshop

- 19 participants
- starting point to understand overall goals of FAIR data publishing
- hands-on experience with data publishing tools
- next step is building a foundation in R programming for team members

# Research Data Management {background-color="#5b195b"}

## Three terms for three stages {.smaller}

| term                                   | explanation                                                                                 | file format                     |
|--------------------|-----------------------|------------------------------|
| unprocessed [raw]{.highlight-yellow} data | data that is not processed and [remains in its original form and file type]{.highlight-yellow} | often XLSX, also CSV and others |

: {.striped tbl-colwidths="\[20, 60, 20\]"}

## Three terms for three stages {.smaller}

| term                                            | explanation                                                                                                       | file format                     |
|--------------------|-----------------------|------------------------------|
| unprocessed [raw]{.highlight-yellow} data          | data that is not processed and [remains in its original form and file type]{.highlight-yellow}     | often XLSX, also CSV and others |
| [processed]{.highlight-yellow} analysis-ready data | data that is processed to [prepare for an analysis]{.highlight-yellow} and is exported in its new form as a new file | CSV, R data package             |

: {.striped tbl-colwidths="\[20, 60, 20\]"}

## Three terms for three stages {.smaller}

| term                                                  | explanation                                                                                                                                                                                  | file format                     |
|--------------------|-----------------------|------------------------------|
| unprocessed [raw]{.highlight-yellow} data                | data that is not processed and [remains in its original form and file type]{.highlight-yellow}                                                                                | often XLSX, also CSV and others |
| [processed]{.highlight-yellow} analysis-ready data       | data that is processed to [prepare for an analysis]{.highlight-yellow} and is exported in its new form as a new file                                                                            | CSV, R data package             |
| [final]{.highlight-yellow} data underlying a publication | data that is the [result of an analysis]{.highlight-yellow} (e.g descriptive statistics or data visualization) and shown in a publication, but then also exported in its new form as a new file | CSV                             |

: {.striped tbl-colwidths="\[20, 60, 20\]"}

# Data Management Strategy {background-color="#5b195b"}

##  {background-image="img/ghe-rdm-workflow-01.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-02.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-03.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-04.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-05.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-06.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-07.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-08.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-09.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-10.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-11.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-12.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-13.drawio.svg" data-background-size="contain" data-background-position="center"}

##  {background-image="img/ghe-rdm-workflow-14.drawio.svg" data-background-size="contain" data-background-position="center"}


::: footer
Diagram at: <https://github.com/Global-Health-Engineering/concept-maps>
:::

# Data steward support

## Data steward for WASH R&D Center

- A fully funded 2-year position, hopefully extended to 5-years with 3rd party funding
- 600 applications, screend to 6, invitations for interviews going out today
- Going through a 12-month programme together with data steward at NGO BASEflow in Malawi

## Data steward activities (WP1) {.incremental}

::: {.incremental}

- Activity 1.3: Identify how ethical approval for data collection differs for types of organizations (university, NGO) and types of data (quantitative, qualitative).

- Activity 1.4: Identify current data management practices and develop a draft data management strategy for organization.

- Activity 1.5: Publish at least 10 datasets of two different types that are available to the organization, following openwashdata data publishing workflow.

:::

## Data steward activities (WP1) 

- Activity 1.3: Identify how ethical approval for data collection differs for types of organizations (university, NGO) and types of data (quantitative, qualitative).

- Activity 1.4: Identify current data management practices and develop a draft data management strategy for organization. **Future**

- Activity 1.5: Publish at least 10 datasets of two different types that are available to the organization, following openwashdata data publishing workflow. **Past** 

## Data steward activities (WP3) 

**Community expansion**

- Activity 3.1: Offer advanced data science training and workshops to community members.
- Activity 3.2: Develop a mentorship program to support new members in adopting ORD practices.
- Activity 3.3: Organize community events to foster networking and collaboration.


## 1st openwashdata forum/retreat/gathering

- Switzerland
- 23rd to 27th June 2025
- Data stewards (Switzerland, Malawi, South Africa)
- Programme to be defined

## data science for openwashdata 002

A the end of the workshop, participants will be able to:

::: {.incremental}
 
1. Be able to use a common set of data science tools (R, RStudio IDE, Git, GitHub, tidyverse, Quarto) to illustrate and communicate the results of data analysis projects.

2. Learn to use the Quarto file format and the RStudio IDE visual editing mode to produce scholarly documents with citations, footnotes, cross-references, figures, and tables.

:::

## data science for openwashdata 002

::: learn-more
[ds4owd-001.github.io/website/](https://ds4owd-001.github.io/website/)

```{=html}
<iframe src="https://ds4owd-001.github.io/website/" width="100%" height="300" style="border:2px solid #123233;" title="Website of data science for openwashdata coursew"></iframe>
```
:::

## data science for openwashdata 002 {.smaller}

- analytics dashboard: <https://openwashdata.github.io/dashboard/dashboard.html>
- analytics data: <https://github.com/openwashdata/analytics>
- graduates 2024: <https://openwashdata.org/pages/academy/graduates/>

## data science for openwashdata 002 {.smaller}

- free, live, online, 10-week programme
- next iteration from Thursday, 11th September 2025 at 13:30 to 16:00 (South Africa timezone)
- Sign-up: <https://forms.gle/MP5rNYZagBdfG2ZRA>

::: learn-more
[ds4owd-001.github.io/website/](https://ds4owd-001.github.io/website/)

```{=html}
<iframe src="https://ds4owd-001.github.io/website/" width="100%" height="300" style="border:2px solid #123233;" title="Website of data science for openwashdata coursew"></iframe>
```
:::

# News {background-color="#5b195b"}

## Support us: Sign up to our newsletter


{{< qrcode https://buttondown.email/openwashdata >}}


<https://buttondown.email/openwashdata>

::: {.content-block}

<iframe
scrolling="no"
style="width:100%!important;height:300px;border:0px !important"
src="https://buttondown.email/openwashdata?as_embed=true"
></iframe><br /><br />

:::


## Thanks `r emo::ji("sunflower")` {.center-align} 

This project was supported by the  [Open Research Data Program of the ETH Board](https://ethrat.ch/en/eth-domain/open-research-data/).

The slides were created via revealjs and Quarto: [https://quarto.org/docs/presentations/revealjs/](https://quarto.org/docs/presentations/revealjs/)

You can [view source code of slides on GitHub](https://github.com/openwashdata/website/blob/main/pages/gallery/slides/ukzn-seminar-02/index.qmd)

Or you can [download slides in PDF format](https://github.com/openwashdata/website/raw/main/pages/gallery/slides/ukzn-seminar/2025-02-06-ukzn-seminar-openwashdata.pdf)

This material is licensed under [Creative Commons Attribution Share Alike 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/).

