---
title: "openwashdata webinar: a data sharing workflow that may please the publishers"
description: |
  In this joint webinar with the Public Library of Science (PLOS) we will introduce you to a workflow for sharing data openly. You will learn about the importance of open data and tangible benefits for sharing.  
bibliography: ../../../references.bib
execute:
    echo: false
    warning: false
editor_options: 
  chunk_output_type: console
---

## 👋 Welcome

Are you wondering why anyone should be interested in your data beyond your project? Do you want to know how to satisfy publisher policies for sharing your data in the process of submitting your scientific article? 

Join us for this joint webinar with PLOS to learn more about:

- the openwashdata community and PLOS Water community
- a workflow for sharing data following FAIR principles for data management @wilkinson2016
- why open data is important 
- tangible benefits of sharing your data
- how PLOS supports open data sharing & open science

## 📆 Event Details

-   **Date:** Tuesday, January 23, 2:00 - 3:00 PM (CET)

-   **Zoom Registration**: <https://ethz.zoom.us/meeting/register/u50lce-vrD0iGN06ywPHr2gPU84Ljr_zmNAf>

-   `r emo::ji("us")` 6:00 AM (MST - Boulder, USA) 
-   `r emo::ji("uk")` 1:00 PM (GMT - London, UK)
-   `r emo::ji("nigeria")` 2:00 PM (WAT - Katsina, Nigeria) 
-   `r emo::ji("kenya")` 4:00 PM (EAT - Nairobi, Kenya)
-   `r emo::ji("india")` 6:30 PM (IST - New Delhi, India)
-   `r emo::ji("indonesia")` 8:00 PM (WIB - Jakarta, Indonesia)

## 📝 Agenda

```{r}
#| tbl-colwidths: [15, 35, 15, 45]
#| column: page

agenda <- readr::read_csv(here::here("pages/events/2023-01-24-webinar-data-publishing/data/tbl-07-webinar-data-sharing-agenda.csv"))

agenda  |> 
    dplyr::select(-start_time, -end_time, -speaker_link, -affiliation_link) |>
    dplyr::relocate(time) |> 
    dplyr::rename_with(~stringr::str_to_title(.x), everything()) |> 
    knitr::kable()
```

## Slides

### openwashdata community & workflow

[View slides in full screen](../../gallery/slides/openwashdata-webinar-01/index.html) | [Download slides as PDF]()

```{=html}
<iframe class="slide-deck" src="../../gallery/slides/openwashdata-webinar-01/index.html" height="420" width="747" style="border: 1px solid #123233;"></iframe>
```

### Open data: A publishers perspective

[View slides in full screen](https://docs.google.com/presentation/d/19dFqFeoteOdkNxxEp0KjDhsVrd3cIrs7k01Xs2g1Kw0/edit#slide=id.g2adbf3af874_0_310)

```{=html}
<iframe class="slide-deck" src="https://docs.google.com/presentation/d/19dFqFeoteOdkNxxEp0KjDhsVrd3cIrs7k01Xs2g1Kw0/edit#slide=id.g2adbf3af874_0_310" height="420" width="747" style="border: 1px solid #123233;"></iframe>
```

## 🏁 Objectives

By the end of this webinar, participants will be able to:

1. Identify where and how to contact the openwashdata team for support with data sharing
2. Describe the benefits of sharing data in addition to a scientific article
3. Rethink current misconceptions about data sharing


