---
title: "GHE Yearly 2025"
subtitle: "openwashdata"
author: 
  - name: "Lars Schöbitz"
    url: https://openwashdata.org/about/lars/
    affiliation: Global Health Engineering, ETH Zurich
    affiliation_url: https://ghe.ethz.ch/
date: 2025-06-02
date-format: long
format: 
  revealjs:
    logo: "../images/OWD-logo-20.png"
    theme: "../../../../style/slides.scss"
    transition: fade
    slide-number: true
    preview-links: auto
    footer: "[{{< fa link >}} openwashdata.org/pages/gallery/slides/](https://openwashdata.org/pages/gallery/slides/)"
editor: source
editor_options: 
  chunk_output_type: console
bibliography: ["../datasets.bib", "../cu-wash-symposium-2023-openwashdata/references.bib"]
---

## openwashdata community

- Launched in 1st March 2023
- Supported by two projects worth 300'000 CHF (50% in-kind contribution)
- Ends in X July 2026

# VMOST to define the vision

## VMOST

- Vision
- Mission
- Objectives
- Strategy
- Tactics

::: speaker-notes
VMOST analysis is a tool used to evaluate if an overall strategy and supporting activities are in alignment. It can be used for current or future plans, and it breaks down a strategy and its core components into an easy-to-consume format 
:::

## Vision

An active global community that applies FAIR principles [@wilkinson2016] to data generated in the great water, sanitation, and hygiene sector.

## Mission

Empower WASH professionals to engage with tools and workflows for open data and code.

## Objectives (Indicators)

### By the end of March 2024 {.scrollable}

::: incremental

1. Increase the number of datasets published on the website to 20 R data packages.
1. Increase the number of datasets that are donated for publication to 50 datasets.
1. Increase the number of people that have donated, cleaned, and published data independently with support of the openwashdata team to 5.
1. Increase the number of unique visitors to the website to 10 visitors/day.
1. Increase global coverage of visitors to the website to 50% of countries globally.
1. Increase the number of data users who report having used data published through openwashdata community to 2 uses per dataset on average.
1. Increase the number of subscribers to the openwashdata newsletter to 250 subscribers from 50 countries.
1. Increase the number of participants in live coding events to 5 participants on average.1. 

:::

## Strategies

- Develop and maintain a data warehouse on the openwashdata website that provides an overview of published datasets.
- Develop a guide as a companion to workshops, live coding events, etc. that documents how to participate in the community and publish data following FAIR principles.
- Build a cohort of students, scientists, practitioners, and civil servants, that are comfortable using R statistical software for exploratory data analysis and Git version control and GitHub for communication and collaboration.
- Prepare all communication material for openwashdata using Quarto publishing framework^[https://quarto.org/] and R statistical software.
- Provide tools and resources to promote the use of open data in the WASH sector
- Publish workshops as open educational material.
- Introduce people to the concept of “open by default”, as well as the use of open source software, the concept of open science, and benefits of open government (data).
- Build material always in mind with learner personas3 that were defined for the community.
- Communication material does not refer to openwashdata as a project, but as a community.
- Design a common corporate identity using defined color palettes, fonts, etc.
- Ensure that material developed for openwashdata follows best practices for accessibility.

## Tactics

- Provide a 10-week online workshop for a selected group of participants to share tools and workflows that support publishing of open data following FAIR principles.
- Publish monthly blog posts on the openwashdata website about selected open datasets, community stories, workflows, insights into community management, use cases, etc.
- Publish monthly issues of the openwashdata newsletter.
- Host quarterly community meetups with invited speakers that share stories from their organisations related to data management, data analysis, open data, etc.
- Visualize and disseminate published open data using interactive dashboards, maps, articles, etc.

## Objectives 2025 to 2026

- ...


## Future of openwashdata

- unclear
- options for future governance are part of current project period
- 

